=== NyAgoston/WH85ZH_XMLGyak/WH85ZH_0928/NYA_kurzusfelvetel.dtd
<!DOCTYPE kurzusfelvetel[
<!ELEMENT kurzusfelvetel (hallgato, kurzusok)>
    <!ELEMENT hallgato (szulnev, szak)>
        <!ELEMENT szulnev>
        <!ELEMENT szak>
    <!ELEMENT kurzusok(kurzus*)>
        <!ELEMENT kurzus(kurzusnev,kredit,hely,idopont,oktato,oraado)>
            <!ELEMENT kurzusnev>
            <!ELEMENT kredit>
            <!ELEMENT hely>
            <!ELEMENT idopont>
            <!ELEMENT oktato>
            <!ELEMENT oraado>


]>

=== NyAgoston/WH85ZH_XMLGyak/WH85ZH_0928/NYA_kurzusfelvétel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE kurzusfelvetel SYSTEM "NYA_kurzusfelvetel.dtd">

<kurzusfelvetel tanev="2022_2023 I." egyetem="ME">

    <hallgato id="KPRLNM.ME">
      <szulnev>2004-04-05</szulnev>
      <szak evf="5">Programtervezo informatikus </szak>
    </hallgato>

   <kurzosok>
    <kurzus id="GEIAL332-B">
      <kurzusnev>Adatkezelés XML kornyezetben</kurzusnev>
      <kredit>5</kredit>
      <hely>XXXII.</hely>
      <idopont>Kedd 12:00-13:30</idopont>
      <oktato>Dr. Bednarik László</oktato>
    </kurzus>

    <kurzus id="GEIAL332-B" jovahagyas="igen">
      <kurzosnev>Adatbazis rendszerek I.</kurzosnev>
      <kredit>5</kredit>
      <hely>In101</hely>
      <idopont>Kedd 08:00-09:30</idopont>
      <oktato>Dr. Kovács László</oktato>
    </kurzus>

    <kurzus id="GEIAL332-B">
      <kurzosnev>Webalkalmazás fejlesztés-Java</kurzosnev>
      <kredit>5</kredit>
      <hely>In103</hely>
      <idopont>Csütörtök 08:00-09:30</idopont>
      <oktato>Dr. Barabás Péter</oktato>
      <oraado>Tóth Bence</oraado>
    </kurzus>
  </kurzosok>
</kurzusfelvetel>

=== NyAgoston/WH85ZH_XMLGyak/WH85ZH_0928/NYA_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE kurzusfelvetel SYSTEM "NYA_kurzusfelvetel.dtd">

<kurzusfelvetel tanev="2022_2023 I." egyetem="ME">

    <hallgato id="KPRLNM.ME">
        <hnev>Nyeste Ágoston</hnev>
        <szulev>2000-06-28</szulev>
        <szak evf="5">Programtervező informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL322-B" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia</kurzusnev>
            <kredit>5</kredit>
            <hely>II A2</hely>
            <idopont>Kedd 09:00-12:00</idopont>
            <oktato>Dr. Kunné Tamás Judit</oktato>
        </kurzus>
        <kurzus id="GEMAK234-B">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>Kedd 12:00-14:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B" jovahagyas="igen">
            <kurzusnev>Algoritmusok és vizsgálat</kurzusnev>
            <kredit>5</kredit>
            <hely>X. A1</hely>
            <idopont>Kedd 14:00-18:00</idopont>
            <oktato>Dr. Házy Attila</oktato>
            <oraado>Dr. Házy Attila</oraado>
        </kurzus>
    </kurzusok>
</kurzusfelvetel>
